service: ts-sample

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs6.10
  timeout: 300
  apiKeys:
      - testing
plugins:
  - serverless-plugin-typescript
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**
  include:
    - webpack.config.js

custom:
  webpackIncludeModules: true

functions:
  hello:
    handler: src/handler.get
    events:
      - http:
          method: get
          path: /hello
          cors: true
          private: true
